export const fontPath = {
    SCDream1: require('../../assets/fonts/SCDream1.otf'),
    SCDream2: require('../../assets/fonts/SCDream2.otf'),
    SCDream3: require('../../assets/fonts/SCDream3.otf'),
    SCDream4: require('../../assets/fonts/SCDream4.otf'),
    SCDream5: require('../../assets/fonts/SCDream5.otf'),
    SCDream6: require('../../assets/fonts/SCDream6.otf'),
    SCDream7: require('../../assets/fonts/SCDream7.otf'),
    SCDream8: require('../../assets/fonts/SCDream8.otf'),
    SCDream9: require('../../assets/fonts/SCDream9.otf'),
}

export const soundPath = {
    balloon: require('../../assets/sound/balloon.mp3'),
    fiesta: require('../../assets/sound/fiesta.mp3'),
    jamaicn: require('../../assets/sound/jamaicnyan.mp3'),
    mummy: require('../../assets/sound/mummy.mp3'),
    pikanya: require('../../assets/sound/pikanyan.mp3'),
    retro: require('../../assets/sound/retro.mp3'),
    wtf: require('../../assets/sound/wtf.mp3'),
}

export const loadingPath = {
    america: require('../../assets/loading/america.gif'),
    daft: require('../../assets/loading/daft.gif'),
    fiesta: require('../../assets/loading/fiesta.gif'),
    j5: require('../../assets/loading/j5.gif'),
    mexinyan: require('../../assets/loading/mexinyan.gif'),
    nyancoin: require('../../assets/loading/nyancoin.gif'),
    paddy: require('../../assets/loading/paddy.gif'),
    retro: require('../../assets/loading/retro.gif'),
    technyancolo: require('../../assets/loading/technyancolor.gif'),
    zombie: require('../../assets/loading/zombie.gif'),
    balloon: require('../../assets/loading/balloon.gif'),
    dub: require('../../assets/loading/dub.gif'),
    jamaicnyan: require('../../assets/loading/jamaicnyan.gif'),
    mummy: require('../../assets/loading/mummy.gif'),
    nyandoge: require('../../assets/loading/nyandoge.gif'),
    pikanyan: require('../../assets/loading/pikanyan.gif'),
    sad: require('../../assets/loading/sad.gif'),
    vday: require('../../assets/loading/vday.gif'),
    bday: require('../../assets/loading/bday.gif'),
    easter: require('../../assets/loading/easter.gif'),
    gb: require('../../assets/loading/gb.gif'),
    jazz: require('../../assets/loading/jazz.gif'),
    nyaninja: require('../../assets/loading/nyaninja.gif'),
    pirate: require('../../assets/loading/pirate.gif'),
    star: require('../../assets/loading/star.gif'),
    wtf: require('../../assets/loading/wtf.gif'),
    breakfast: require('../../assets/loading/breakfast.gif'),
    elevator: require('../../assets/loading/elevator.gif'),
    grumpy: require('../../assets/loading/grumpy.gif'),
    melon: require('../../assets/loading/melon.gif'),
    nyanCat: require('../../assets/loading/nyan-cat-1.gif'),
    original: require('../../assets/loading/original.gif'),
    pumpkin: require('../../assets/loading/pumpkin.gif'),
    tacnayn: require('../../assets/loading/tacnayn.gif'),
    xma: require('../../assets/loading/xmas.gif')
}

export const animationPath = {
    heart: require('../../assets/animation/heart.json'),
    loading: require('../../assets/animation/loading.json'),
    confetti: require('../../assets/animation/confetti.json'),
    found: require('../../assets/animation/found.json'),
    chilling: require('../../assets/animation/chilling.json'),
    ninja: require('../../assets/animation/ninja.json'),
}